global:
  scrape_interval: 15s        # KÃ¼si andmeid iga 15 sekundi tagant

scrape_configs:
  - job_name: 'shoehub'       # Nimi, mis ilmub Prometheus UI's
    static_configs:
      - targets: ['shoehub:8080']  # Docker network'is konteineri nimi, MITTE localhost
